name: test03

on:
  push:
    branches: [ master, develop, release, codedrop ]
  pull_request:
    branches: [ master, develop, release, codedrop ]

jobs:
  win_build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
        working-directory: pengzedong/MT-test
        


    steps:
    - name: Checkout swmm repo
      uses: actions/checkout@v2
      
    - name: Checkout test repo
      uses: actions/checkout@v2
      with:
        repository: pengzedong/MT-test
        ref: master

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - shell: cmd
      run: |
        run-test1.cmd
    
