name: test03

on:
  push:
    branches: [ master, develop, release, codedrop ]
  pull_request:
    branches: [ master, develop, release, codedrop ]

jobs:
  win_build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
        working-directory: pengzedong/MT-test
        


    steps:
    - name: Checkout swmm repo
      uses: actions/checkout@v2
      
    - name: Checkout test repo
      uses: actions/checkout@v2
      with:
        repository: pengzedong/MT-test
        ref: master
        path: MT-test

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - shell: cmd
      run: |
        python MT-python.py 3 4 >temp1.txt
        set /P value=<temp1.txt
        echo %value%
        python MT-checker-python.py 3 4 %value%
